# 바이너리에 특정 심볼 패턴이 **없는지** 확인한다 (컴포넌트 격리 검사).
#   cmake -DBIN=<바이너리> -DNM=<nm 경로> -DPATTERN=<패턴> -DWHAT=<설명> -P check_absent.cmake
execute_process(COMMAND ${NM} -C ${BIN} OUTPUT_VARIABLE syms RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
    message(FATAL_ERROR "nm 실패: ${BIN}")
endif()
string(REPLACE "\n" ";" lines "${syms}")
set(hits 0)
foreach(l ${lines})
    string(FIND "${l}" "${PATTERN}" pos)
    if(NOT pos EQUAL -1)
        math(EXPR hits "${hits}+1")
        if(hits LESS 4)
            message("  누출: ${l}")
        endif()
    endif()
endforeach()
if(hits GREATER 0)
    message(FATAL_ERROR "${BIN} 에 ${WHAT} 심볼이 ${hits}개 있다 -- 컴포넌트 격리가 깨졌다")
endif()
message("OK: ${BIN} 에 ${WHAT} 심볼 없음")
